language: node_js

node_js:
  - '0.10'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - gulp test
  - gulp build

deploy:
  provider: heroku
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: qj5EPGLJmcdiK6XbfBN9B7UCBelBJnB49alkCGneOdxmFJTgMK+nyXqw69aHJYyioSJYIOchSQXBvD0U6jfqQu6I18nRPqIQoH+4xD+XtPiIiyfxsWrq9eus/CSKQQ+xE0AyjuSooUjBlVoAuZMc64ujIeuhDZf36q189xwF5a0=
  app: ng-range-slider
  on:
    repo: Wildhoney/ngRangeSlider